services:
  users-service:
    build: ./users-service
    working_dir: /users-service/users-service
    volumes:
      - .:/users-service
    ports:
      - 8000:8000
    environment:
      SECRET_KEY_FILE: /run/secrets/secret-key
      POSTGRES_HOST: users-db:5432
      POSTGRES_USER: users
      POSTGRES_PASSWORD_FILE: /run/secrets/users-db-password
      POSTGRES_DB: database
    depends_on:
      users-db:
        condition: service_healthy
    secrets:
      - users-db-password
      - secret-key

  users-db:
    image: postgres:15.2
    environment:
      POSTGRES_DATABASE: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD_FILE: /run/secrets/users-db-password
      POSTGRES_DB: database
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - users-db-data:/var/lib/postgresql/data
    secrets:
      - users-db-password

  frontend-service:
    build: ./frontend-service
    environment:
      REACT_APP_USERS_SERVICE_URL: http://localhost:8000
      WATCHPACK_POLLING: true
    command: npm start
    volumes:
      - ./frontend-service/src:/frontend-service/src
    ports:
      - 3000:3000
    depends_on:
      - users-service

secrets:
  users-db-password:
    file: ./secrets/users-db-password.txt
  secret-key:
    file: ./secrets/secret-key.txt

volumes:
  users-db-data:
