version: "3.8"

services:
  users-service:
    build: ./users-service
    working_dir: /users-service/users-service
    volumes:
      - .:/users-service
    expose:
      - 8001
    environment:
      POSTGRES_HOST: users-db:5432
      POSTGRES_USER: users
      POSTGRES_PASSWORD_FILE: /run/secrets/users-db-password
      POSTGRES_DB: database
    depends_on:
      users-db:
        condition: service_healthy
    secrets:
      - users-db-password

  users-db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD_FILE: /run/secrets/users-db-password
      POSTGRES_DB: database
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users -d database"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - users-db-data:/var/lib/postgresql/data
    secrets:
      - users-db-password

  messages-service:
    build: ./messages-service
    working_dir: /messages-service/messages-service
    volumes:
      - .:/messages-service
    expose:
      - 8002
    environment:
      POSTGRES_HOST: messages-db:5432
      POSTGRES_USER: messages
      POSTGRES_PASSWORD_FILE: /run/secrets/messages-db-password
      POSTGRES_DB: database
    depends_on:
      messages-db:
        condition: service_healthy

  messages-db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: messages
      POSTGRES_PASSWORD_FILE: /run/secrets/messages-db-password
      POSTGRES_DB: database
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U messages -d database"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - messages-db-data:/var/lib/postgresql/data
    secrets:
      - messages-db-password

  api-gateway:
    build: ./api-gateway
    working_dir: /api-gateway/api-gateway
    volumes:
      - .:/api-gateway
    ports:
      - 8000:8000
    environment:
      USERS_SERVICE_URL: http://users-service:8001
      MESSAGES_SERVICE_URL: http://messages-service:8002
    depends_on:
      - users-service
      - messages-service

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_GATEWAY_URL: http://localhost:8000
      REACT_APP_API_GATEWAY_WS_URL: ws://localhost:8000
      WATCHPACK_POLLING: true
    command: npm start
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - 3000:3000
    depends_on:
      - api-gateway

secrets:
  users-db-password:
    file: ./secrets/users-db-password.txt
  messages-db-password:
    file: ./secrets/messages-db-password.txt

volumes:
  users-db-data:
  messages-db-data:
