services:
  users-service:
    build: ./users-service
    working_dir: /users-service/users-service
    volumes:
      - .:/users-service
    ports:
      - 8000:8000
    environment:
      DB_HOST: users-db:3306
      DB_USER: users
      DB_PASSWORD_FILE: /run/secrets/users-db-password
    depends_on:
      users-db:
        condition: service_healthy
    secrets:
      - users-db-password

  users-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/users-db-root-password
      MYSQL_DATABASE: users
      MYSQL_USER: users
      MYSQL_PASSWORD_FILE: /run/secrets/users-db-password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - users-db-data:/var/lib/mysql
    secrets:
      - users-db-password
      - users-db-root-password

secrets:
  users-db-password:
    file: ./secrets/users-db-password.txt
  users-db-root-password:
    file: ./secrets/users-db-root-password.txt

volumes:
  users-db-data:
